'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,BookOpen,Check,CheckCircle2,ChevronRight,Clock3,Copy,FileText,Globe2,Landmark,LayoutDashboard,LockKeyhole,MapPin,Menu,MessageSquare,Search,ShieldCheck,ShieldAlert,Scale,Users, X, Megaphone, Plus, Download, CircleHelp} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import JusticeScene from './justice-scene';
import {messages} from '@/lib/i18n';

type Ticket={id:string;subject:string;category:string;office:string;status:string;date:string};
type Notice={id:number;title:string;body:string;kind:string};
const initialTickets:Ticket[]=[{id:'DEMO-2026-0142',subject:'Request for service clarification',category:'Public service',office:'Jinka',status:'In review',date:'23 Sep 2026'},{id:'DEMO-2026-0141',subject:'Document access inquiry',category:'Legal information',office:'Bena-Tsemay',status:'Received',date:'22 Sep 2026'},{id:'DEMO-2026-0140',subject:'Mediation referral request',category:'Mediation',office:'Hamer',status:'Resolved',date:'21 Sep 2026'},{id:'DEMO-2026-0139',subject:'Service delivery feedback',category:'Public service',office:'Jinka',status:'In review',date:'20 Sep 2026'}];
const guides=[{title:'Your guide to submitting a complaint',category:'Citizen guides',text:'Prepare a clear summary of the issue, relevant dates, and the office involved. Keep copies of supporting documents. For this demonstration, use fictional information only. Official submission channels and timelines must be confirmed with the department.'},{title:'Understanding the complaint process',category:'Citizen guides',text:'The illustrative process is: receipt, initial review, referral or investigation, and response. A tracking reference connects each stage. This sample does not define official deadlines or guarantee an outcome.'},{title:'Preparing for a mediation referral',category:'Customary justice',text:'Bring a summary of the dispute and identify the parties involved. Ask the responsible justice office whether mediation is appropriate. Participation, safeguards, and available alternatives must be explained by the authorized service provider.'},{title:'Public information and service access',category:'Service charter',text:'Ask the responsible office about the records and services you need, the required documents, applicable fees, and appeal options. Official service charters and legislation will be added after verification.'}];
const offices=['Jinka','Bena-Tsemay','Hamer','Dasenech','Nyangatom','South Ari'];
function Choice({value,onChange,items,label}:{value:string;onChange:(s:string)=>void;items:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
export default function Portal({initialView='home'}:{initialView?:'home'|'admin'}){
 const [view,setView]=useState(initialView),[lang,setLang]=useState<'en'|'am'>('en'),[mobile,setMobile]=useState(false),[modal,setModal]=useState<string|null>(null);
 const [adminSection,setAdminSection]=useState('overview');
 const [tickets,setTickets]=useState<Ticket[]>(initialTickets),[notices,setNotices]=useState<Notice[]>([{id:1,title:'A simpler way to reach justice services',body:'Explore complaint tracking, citizen information, and local service access in this portal preview.',kind:'Service update'}]);
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All resources'),[resource,setResource]=useState<typeof guides[number]|null>(null),[office,setOffice]=useState('Jinka');
 const [tracking,setTracking]=useState(''),[tracked,setTracked]=useState<Ticket|null>(null),[trackingError,setTrackingError]=useState('');
 const [step,setStep]=useState(1),[category,setCategory]=useState('Public service'),[summary,setSummary]=useState(''),[receipt,setReceipt]=useState<Ticket|null>(null),[formError,setFormError]=useState('');
 const [adminSearch,setAdminSearch]=useState(''),[statusFilter,setStatusFilter]=useState('All statuses'),[selected,setSelected]=useState<Ticket|null>(null),[newStatus,setNewStatus]=useState(''),[noticeTitle,setNoticeTitle]=useState(''),[noticeBody,setNoticeBody]=useState(''),[noticeKind,setNoticeKind]=useState('Service update');
 const t=messages[lang];
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 const navigate=(target:string)=>{setView('home');setMobile(false);setTimeout(()=>document.getElementById(target)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'}),20);};
 const openComplaint=(whistle=false)=>{setStep(1);setSummary('');setReceipt(null);setFormError('');setCategory(whistle?'Whistleblower report':'Public service');setModal('complaint');};
 const track=(id:string)=>{const ticket=tickets.find(x=>x.id.toUpperCase()===id.trim().toUpperCase());setTracked(ticket??null);setTrackingError(ticket?'':'No sample record matches this reference. Try DEMO-2026-0142.');return ticket;};
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const controller=new AbortController();try{Promise.resolve(ctx.registerTool({name:'start_complaint_tracking',description:'Open the sample complaint tracking form. Does not submit or change a complaint.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object');setModal('track');return {opened:'sample complaint tracking'};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[]);
 const submitDemo=()=>{const record={id:'DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase(),subject:summary.trim(),category,office,status:'Received',date:'This session'};setTickets(prev=>[record,...prev]);setReceipt(record);setStep(3);};
 const filtered=tickets.filter(x=>(statusFilter==='All statuses'||x.status===statusFilter)&&(x.id+' '+x.subject+' '+x.office).toLowerCase().includes(adminSearch.toLowerCase()));
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);toast.success('Reference copied');}catch{toast.error('Copy unavailable. Please select and copy the reference.');}};
 return <><Toaster position="bottom-right"/><a className="skip-link" href="#main">Skip to content</a>
 {view==='home'&&<><div className="utility"><div className="container utility-inner"><span><Landmark size={13}/> South Ethiopia Regional State <span className="utility-divider">/</span> South Omo Zone</span><div><span className="preview-label">DESIGN PREVIEW</span><button onClick={()=>setLang(lang==='en'?'am':'en')}><Globe2 size={14}/>{lang==='en'?'አማርኛ':'English'}</button></div></div></div>
 <header className="site-header"><div className="container header-inner"><button className="brand" onClick={()=>{setView('home');window.scrollTo(0,0)}} aria-label="South Omo Justice home"><img src="/justice-logo.png" alt="S/E/R/State Bureau of Justice logo"/><span><strong>South Omo Zone</strong><b>Justice Department</b><small lang="am">የደቡብ ኦሞ ዞን ፍትሕ መምሪያ</small></span></button><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><nav className={mobile?'nav open':'nav'} aria-label="Main navigation"><button className="active" onClick={()=>navigate('main')}>{t.home}</button><button onClick={()=>navigate('services')}>{t.services}</button><button onClick={()=>navigate('resources')}>{t.resources}</button><button onClick={()=>navigate('customary')}>{t.customary}</button><button className="admin-link" onClick={()=>{setView('admin');setAdminSection('overview');setMobile(false);window.scrollTo(0,0)}}><LockKeyhole size={15}/>{t.admin}</button></nav></div></header></>}
 {view==='home'?<main id="main">
  <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow light"><span/>{t.eyebrow}</div><h1>{t.title}<br/><em>{t.accent}</em></h1><p>{t.intro}</p><div className="hero-buttons"><button className="button cyan" onClick={()=>openComplaint()}>{t.complaint}<ArrowUpRight size={18}/></button><button className="button ghost" onClick={()=>setModal('track')}>{t.track}<ArrowRight size={17}/></button></div><div className="hero-assurance"><ShieldCheck size={17}/>{t.heroNote}</div></div><JusticeScene/></div><div className="hero-bottom"><div className="container"><span><Scale size={16}/> Fairness in every decision.</span><span><Users size={16}/> Dignity for every person.</span><span><Landmark size={16}/> Accountability in every action.</span></div></div></section>
  <div className="notice-strip"><div className="container"><span className="notice-kicker"><Megaphone size={16}/>PUBLIC NOTICE</span><p>{notices[0]?.title??'No current notices'}</p><button onClick={()=>setModal('notices')}>View updates <ArrowRight size={15}/></button></div></div>
  <section id="services" className="container section"><div className="section-heading"><div><div className="eyebrow">{t.sectionLabel}</div><h2>{t.serviceTitle}</h2></div><p>{t.serviceIntro}</p></div><div className="service-grid">
   {[{icon:MessageSquare,title:'Complaints & requests',text:'Raise a concern and follow its progress, one step at a time.',label:'Start a complaint',action:()=>openComplaint()},{icon:BookOpen,title:'Know your rights',text:'Find citizen guides, legal resources, and service information.',label:'Browse resources',action:()=>navigate('resources')},{icon:MapPin,title:'Find your justice office',text:'Connect with justice services closer to your community.',label:'Explore local offices',action:()=>setModal('offices')},{icon:ShieldAlert,title:'Speak up safely',text:'Learn how a confidential reporting service could work.',label:'Whistleblower preview',action:()=>openComplaint(true)}].map((s,i)=><button className={'service-card service-'+i} key={s.title} onClick={s.action}><div className="service-card-top"><span className="icon-tile"><s.icon size={24} strokeWidth={1.5}/></span><ArrowUpRight size={18}/></div><h3>{s.title}</h3><p>{s.text}</p><span className="card-link">{s.label}<ArrowRight size={15}/></span></button>)}
  </div></section>
  <section className="container access-row"><div className="track-panel"><div className="round-icon"><Search size={24}/></div><div><div className="eyebrow">STAY INFORMED</div><h3>Your complaint. A clear next step.</h3><p>Use your reference number to view a sample case journey.</p><form className="inline-form" onSubmit={e=>{e.preventDefault();track(tracking);setModal('track')}}><label className="sr-only" htmlFor="quick-track">Complaint reference</label><input id="quick-track" value={tracking} onChange={e=>setTracking(e.target.value)} placeholder="e.g. DEMO-2026-0142" required/><button className="button navy" type="submit">Track <ArrowRight size={16}/></button></form></div></div><div className="commitment"><ShieldCheck size={27}/><h3>Public service.<br/>Built on public trust.</h3><p>Accessible information, transparent processes, and respect for every voice.</p></div></section>
  <section id="resources" className="container section resources"><div className="section-heading"><div><div className="eyebrow">INFORMATION IS EMPOWERMENT</div><h2>Understand your next step.</h2></div><span className="small-note">Illustrative citizen guides · English</span></div><div className="resource-controls"><div className="search-field"><Search size={18}/><input aria-label="Search legal resources" placeholder="Search guides and resources…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Choice label="Resource category" value={filter} onChange={setFilter} items={['All resources','Citizen guides','Customary justice','Service charter']}/></div><div className="resource-grid">{guides.filter(x=>(filter==='All resources'||x.category===filter)&&(x.title+' '+x.category).toLowerCase().includes(query.toLowerCase())).map((g,i)=><button className="resource-card" key={g.title} onClick={()=>{setResource(g);setModal('resource')}}><span className="resource-number">0{guides.indexOf(g)+1}</span><span className="resource-category">{g.category}</span><h3>{g.title}</h3><div><span><FileText size={14}/> Reading guide</span><ArrowUpRight size={19}/></div></button>)}</div>{!guides.some(x=>(filter==='All resources'||x.category===filter)&&(x.title+' '+x.category).toLowerCase().includes(query.toLowerCase()))&&<p className="empty-state">No matching guides. Try another search or category.</p>}</section>
  <section id="customary" className="heritage-section"><div className="container heritage-grid"><div className="heritage-symbol"><Users size={68} strokeWidth={1}/><span>COMMUNITY · DIALOGUE · RECONCILIATION</span></div><div><div className="eyebrow">ROOTED IN COMMUNITY</div><h2>Honoring tradition.<br/>Upholding justice.</h2><p>Explore the role of dialogue and reconciliation in customary justice, alongside the protections of the formal legal system.</p><button className="text-button" onClick={()=>{setResource(guides[2]);setModal('resource')}}>Explore customary justice <ArrowRight size={18}/></button></div></div></section>
  <section className="container contact-section"><div><div className="eyebrow">CLOSER TO YOUR COMMUNITY</div><h2>Find a path to local support.</h2><p>Explore the office directory preview for South Omo.</p></div><button className="button navy" onClick={()=>setModal('offices')}><MapPin size={17}/>Find a justice office<ArrowUpRight size={17}/></button></section>
 </main>:<main id="main" className="admin-main">
  <Tabs value={adminSection} onValueChange={setAdminSection} orientation="vertical" className="admin-shell">
   <aside className="admin-sidebar">
    <button className="admin-brand" onClick={()=>setAdminSection('overview')} aria-label="Admin overview"><img src="/justice-logo.png" alt="Bureau of Justice logo"/><span><strong>South Omo Justice</strong><small>Administration</small></span></button>
    <div className="sidebar-label">WORKSPACE</div>
    <TabsList className="admin-side-nav"><TabsTrigger value="overview"><LayoutDashboard size={18}/><span>Overview</span></TabsTrigger><TabsTrigger value="complaints"><MessageSquare size={18}/><span>Complaints</span><b>{tickets.filter(x=>x.status!=='Resolved').length}</b></TabsTrigger><TabsTrigger value="notices"><Megaphone size={18}/><span>Public notices</span></TabsTrigger><TabsTrigger value="configuration"><ShieldCheck size={18}/><span>Access & readiness</span></TabsTrigger></TabsList>
    <div className="admin-sidebar-bottom"><span className="sidebar-user"><span>AD</span><span><strong>Administrator</strong><small>Design preview</small></span></span><button onClick={()=>{setView('home');window.scrollTo(0,0)}}><ArrowRight size={17}/><span>Return to public portal</span></button></div>
   </aside>
   <div className="admin-workspace">
    <header className="admin-topbar"><div><span className="admin-breadcrumb">ADMIN WORKSPACE <ChevronRight size={13}/>{adminSection==='overview'?'Overview':adminSection==='complaints'?'Complaints':adminSection==='notices'?'Public notices':'Access & readiness'}</span></div><div className="admin-top-actions"><span className="preview-label">DESIGN PREVIEW</span><button onClick={()=>setLang(lang==='en'?'am':'en')}><Globe2 size={15}/>{lang==='en'?'አማርኛ':'English'}</button><span className="admin-badge"><ShieldCheck size={15}/>Administrator</span></div></header>
    <div className="admin-content">
     <TabsContent value="overview"><div className="admin-heading"><div><div className="eyebrow">SERVICE OVERVIEW</div><h1>Good morning.</h1><p>Here is what needs attention in the justice service workspace.</p></div><span className="workspace-date">23 September 2026</span></div><div className="demo-banner"><CircleHelp size={19}/><p><strong>Sample workspace.</strong> All records are fictional. Changes last until this page is refreshed. Authentication and live case storage are not connected.</p></div><div className="stats-grid">{[{label:'Total complaints',value:tickets.length,icon:FileText},{label:'Awaiting review',value:tickets.filter(x=>x.status==='Received').length,icon:Clock3},{label:'In review',value:tickets.filter(x=>x.status==='In review').length,icon:Search},{label:'Resolved',value:tickets.filter(x=>x.status==='Resolved').length,icon:CheckCircle2}].map(s=><button className="stat-card" key={s.label} onClick={()=>setAdminSection('complaints')}><span>{s.label}<s.icon size={19}/></span><strong>{s.value.toString().padStart(2,'0')}</strong><small>View complaint register <ArrowRight size={13}/></small></button>)}</div><section className="admin-panel overview-panel"><div className="panel-heading"><div><h2>Recent complaints</h2><p>The latest sample records requiring staff attention.</p></div><button className="text-button" onClick={()=>setAdminSection('complaints')}>View all complaints<ArrowRight size={16}/></button></div><div className="overview-list">{tickets.slice(0,3).map(x=><button key={x.id} onClick={()=>{setSelected(x);setNewStatus(x.status);setModal('review')}}><span className="overview-list-icon"><FileText size={18}/></span><span><strong>{x.subject}</strong><small>{x.id} · {x.office} · {x.date}</small></span><span className={'status '+x.status.toLowerCase().replace(' ','-')}>{x.status}</span><ChevronRight size={17}/></button>)}</div></section></TabsContent>
     <TabsContent value="complaints"><div className="admin-heading compact"><div><div className="eyebrow">CASE MANAGEMENT</div><h1>Complaints</h1><p>Search, review, and update public service complaints.</p></div></div><section className="admin-panel"><div className="panel-heading"><div><h2>Complaint register</h2><p>Review a record to update its sample status.</p></div><button className="button outline" onClick={()=>{const rows=[['Reference','Subject','Category','Office','Status'],...tickets.map(x=>[x.id,x.subject,x.category,x.office,x.status])];const csv=rows.map(row=>row.map(s=>'"'+s.replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download='south-omo-sample-register.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}><Download size={16}/>Export sample CSV</button></div><div className="resource-controls"><div className="search-field"><Search size={18}/><input aria-label="Search complaint register" placeholder="Search reference, subject or office…" value={adminSearch} onChange={e=>setAdminSearch(e.target.value)}/></div><Choice label="Filter status" value={statusFilter} onChange={setStatusFilter} items={['All statuses','Received','In review','Resolved']}/></div><Table><TableHeader><TableRow>{['Reference / received','Subject','Office','Status','Action'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(x=><TableRow key={x.id}><TableCell><strong className="reference">{x.id}</strong><small className="table-sub">{x.date}</small></TableCell><TableCell>{x.subject}<small className="table-sub">{x.category}</small></TableCell><TableCell>{x.office}</TableCell><TableCell><span className={'status '+x.status.toLowerCase().replace(' ','-')}>{x.status}</span></TableCell><TableCell><button className="review-button" onClick={()=>{setSelected(x);setNewStatus(x.status);setModal('review')}}>Review<ChevronRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<p className="empty-state">No complaints match your filters.</p>}<div className="table-foot">{filtered.length} of {tickets.length} sample complaints</div></section></TabsContent>
     <TabsContent value="notices"><div className="admin-heading compact"><div><div className="eyebrow">CONTENT MANAGEMENT</div><h1>Public notices</h1><p>Create and manage updates shown on the public portal.</p></div></div><section className="admin-panel"><div className="panel-heading"><div><h2>Published notices</h2><p>The latest item appears on the public homepage.</p></div><button className="button navy" onClick={()=>{setNoticeTitle('');setNoticeBody('');setModal('new-notice')}}><Plus size={16}/>Create notice</button></div>{notices.map(n=><article className="notice-row" key={n.id}><Megaphone size={22}/><div><span className="resource-category">{n.kind}</span><h3>{n.title}</h3><p>{n.body}</p></div><button className="text-button danger" onClick={()=>{setNotices(prev=>prev.filter(x=>x.id!==n.id));toast.success('Sample notice unpublished')}}>Unpublish</button></article>)}{!notices.length&&<p className="empty-state">No sample notices published.</p>}</section></TabsContent>
     <TabsContent value="configuration"><div className="admin-heading compact"><div><div className="eyebrow">SYSTEM READINESS</div><h1>Access & readiness</h1><p>Review the controls required before operational launch.</p></div></div><section className="admin-panel readiness"><h2>Before this becomes a live service</h2><p>This is an interactive design preview, not an authenticated government system.</p>{['Verify office contacts, official documents and service procedures.','Connect staff sign-in and enforce server-side access roles.','Configure protected case storage, retention and audit logging.','Review complaint privacy, anonymous reporting and incident response.','Complete accessibility, translation and security testing.'].map(x=><p key={x}><ShieldCheck size={19}/>{x}</p>)}</section></TabsContent>
    </div>
   </div>
  </Tabs>
 </main>}
 {view==='home'&&<footer><div className="container footer-top"><div className="footer-brand"><img src="/justice-logo.png" alt="Bureau of Justice logo"/><div><strong>South Omo Zone Justice Department</strong><span>{t.footer}</span></div></div><div className="footer-links"><button onClick={()=>navigate('resources')}>Citizen resources</button><button onClick={()=>setModal('offices')}>Office directory</button><button onClick={()=>setModal('about')}>About this preview</button></div></div><div className="container footer-bottom"><span>© 2026 South Omo Zone Justice Department · Design concept</span><span>Serving people. Strengthening justice.</span></div></footer>}
 <Dialog open={modal!==null} onOpenChange={open=>{if(!open)setModal(null)}}><DialogContent className="portal-modal"><DialogTitle>{modal==='track'?'Track your complaint':modal==='complaint'?(category==='Whistleblower report'?'Whistleblower service preview':'Complaint service preview'):modal==='resource'?resource?.title:modal==='offices'?'Local justice offices':modal==='review'?'Review sample complaint':modal==='new-notice'?'Create a sample notice':modal==='notices'?'Public notices':'About this portal preview'}</DialogTitle><DialogDescription>{modal==='resource'?'Illustrative guidance · not an official legal document':modal==='offices'?'Directory concept. Official service locations and contact details require verification.':modal==='review'||modal==='new-notice'?'Changes apply to this demonstration session only.':'Interactive design preview. No information is sent to a government office.'}</DialogDescription>
 {modal==='track'&&<><form onSubmit={e=>{e.preventDefault();track(tracking)}} className="modal-form"><label htmlFor="track-id">Reference number</label><div className="inline-form"><input id="track-id" value={tracking} required onChange={e=>{setTracking(e.target.value);setTracked(null);setTrackingError('')}} placeholder="DEMO-2026-0142"/><button className="button navy">Track</button></div><button type="button" className="text-button" onClick={()=>{setTracking('DEMO-2026-0142');track('DEMO-2026-0142')}}>Try a sample reference<ArrowRight size={15}/></button></form>{trackingError&&<p role="alert" className="error">{trackingError}</p>}{tracked&&<div className="tracking-result" aria-live="polite"><div className="result-head"><strong>{tracked.id}</strong><span className={'status '+tracked.status.toLowerCase().replace(' ','-')}>{tracked.status}</span></div><p>{tracked.subject}</p><ol className="timeline">{['Received','In review','Resolved'].map((s,i)=>{const complete=i<=['Received','In review','Resolved'].indexOf(tracked.status);return <li className={complete?'complete':''} key={s}><span>{complete?<Check size={15}/>:i+1}</span><div><strong>{s}</strong><p>{i===0?'Sample reference created':i===1?'Assigned for initial assessment':'Response recorded and case closed'}</p></div></li>})}</ol></div>}</>}
 {modal==='complaint'&&<><div className="demo-banner"><ShieldAlert size={20}/><p>Use fictional information only. This preview has no confidential intake, file storage, or anonymous reporting protection.</p></div><div className="step-labels">{['Details','Review','Receipt'].map((x,i)=><span key={x} className={step>=i+1?'current':''}>{i+1}. {x}</span>)}</div>{step===1?<form className="modal-form" onSubmit={e=>{e.preventDefault();if(summary.trim().length<10){setFormError('Enter at least 10 characters for the sample summary.');return;}setFormError('');setStep(2)}}><label>Service category</label><Choice label="Complaint category" value={category} onChange={setCategory} items={['Public service','Legal information','Mediation','Whistleblower report']}/><label>Office</label><Choice label="Complaint office" value={office} onChange={setOffice} items={offices}/><label htmlFor="summary">Fictional complaint summary</label><textarea id="summary" value={summary} onChange={e=>setSummary(e.target.value)} minLength={10} maxLength={500} required placeholder="Describe a sample service concern…"/>{formError&&<p role="alert" className="error">{formError}</p>}<button className="button navy">Review sample<ArrowRight size={16}/></button></form>:step===2?<div className="review-summary"><span className="resource-category">{category} · {office}</span><h3>Check your sample details</h3><p>{summary}</p><div className="modal-actions"><button className="button outline" onClick={()=>setStep(1)}>Back</button><button className="button navy" onClick={submitDemo}>Create sample ticket<Check size={16}/></button></div></div>:receipt&&<div className="receipt"><CheckCircle2 size={42}/><h3>Sample ticket created</h3><p>No complaint has been submitted to the department.</p><button className="receipt-code" onClick={()=>copy(receipt.id)}>{receipt.id}<Copy size={16}/></button><p>Use this reference while this page remains open. Refreshing clears the sample record.</p><button className="button navy" onClick={()=>{setTracking(receipt.id);setTracked(receipt);setModal('track')}}>View sample progress<ArrowRight size={16}/></button></div>}</>}
 {modal==='resource'&&resource&&<div className="guide-body"><span className="resource-category">{resource.category}</span><p>{resource.text}</p><div className="guide-note"><BookOpen size={20}/><p>Verified proclamations, regulations and official PDF documents have not yet been supplied for this portal.</p></div></div>}
 {modal==='offices'&&<div className="office-directory"><div className="office-buttons">{offices.map(x=><button className={office===x?'chosen':''} onClick={()=>setOffice(x)} key={x}><MapPin size={16}/>{x}</button>)}</div><div className="office-detail"><Landmark size={32}/><h3>{office} service area</h3><p>This entry illustrates the office directory. Confirm the office address, telephone number and opening hours before using it for a visit.</p><span className="status received">Contact details awaiting verification</span></div></div>}
 {modal==='review'&&selected&&<div className="modal-form"><span className="reference">{selected.id}</span><h3>{selected.subject}</h3><p>{selected.category} · {selected.office}</p><label>Sample case status</label><Choice label="Update case status" value={newStatus} onChange={setNewStatus} items={['Received','In review','Resolved']}/><button className="button navy" onClick={()=>{setTickets(prev=>prev.map(x=>x.id===selected.id?{...x,status:newStatus}:x));setTracked(prev=>prev?.id===selected.id?{...prev,status:newStatus}:prev);setModal(null);toast.success('Sample status updated')}}>Save status<Check size={16}/></button></div>}
 {modal==='new-notice'&&<form className="modal-form" onSubmit={e=>{e.preventDefault();if(!noticeTitle.trim()||!noticeBody.trim())return;setNotices(prev=>[{id:Date.now(),title:noticeTitle.trim(),body:noticeBody.trim(),kind:noticeKind},...prev]);setModal(null);toast.success('Sample notice published')}}><label htmlFor="notice-title">Title</label><input id="notice-title" required maxLength={120} value={noticeTitle} onChange={e=>setNoticeTitle(e.target.value)}/><label>Notice type</label><Choice label="Notice type" value={noticeKind} onChange={setNoticeKind} items={['Service update','Public notice','Urgent notice']}/><label htmlFor="notice-body">Message</label><textarea id="notice-body" required maxLength={800} value={noticeBody} onChange={e=>setNoticeBody(e.target.value)}/><button className="button navy">Publish sample notice<ArrowRight size={16}/></button></form>}
 {modal==='notices'&&<div>{notices.map(n=><article className={'public-notice '+(n.kind==='Urgent notice'?'urgent':'')} key={n.id}><span className="resource-category">{n.kind}</span><h3>{n.title}</h3><p>{n.body}</p></article>)}{!notices.length&&<p>No sample notices are currently published.</p>}</div>}
 {modal==='about'&&<div className="guide-body"><p>A design concept for the South Omo Zone Justice Department using the supplied regional Bureau of Justice logo and justice color system.</p><p>Complaint records, guides and notices are illustrative. No official contacts, legal documents or operational service data have been verified. This preview does not collect or securely store real complaints.</p><p>The Amharic switch previews the primary navigation and homepage introduction; detailed service workflows are currently in English.</p></div>}
 </DialogContent></Dialog></>;
}
