'use client';
import React,{useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUp,BellRing,CalendarDays,ChevronLeft,ChevronRight,Clock,Copy,Download,Expand,FileText,Images,Mail,MapPin,Megaphone,Pin,Printer,Share2,Trash2,Upload,User} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {toast} from 'sonner';
import {Content,GalleryItem,faqs,events} from '@/lib/content';
import {usePortal,useT,Intro,Action,Badge,copy,Field} from '@/components/justice-portal';

const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export function fmtDate(d?:string){if(!d)return 'Date to be confirmed';const [y,m,day]=d.split('-').map(Number);return `${day} ${months[m-1]} ${y}`}
const byDate=(a:Content,b:Content)=>(b.date||'').localeCompare(a.date||'');
const readMinutes=(item:Content)=>Math.max(1,Math.round([item.content_en,...(item.body||[])].join(' ').split(/\s+/).length/200));
function DateBlock({d}:{d?:string}){if(!d)return null;const [,m,day]=d.split('-').map(Number);return <div className="date-block" aria-hidden><strong>{day}</strong><span>{months[m-1]}</span></div>}

/* ---------- Notice board ---------- */
export function NoticeTicker(){const {items,lang}=usePortal(),t=useT();const list=items.filter(x=>x.kind==='notices'&&x.published).sort(byDate);if(!list.length)return null;return <div className="ticker"><div className="wrap ticker-inner"><span className="ticker-label"><BellRing size={16}/>{t('Latest notices','የቅርብ ጊዜ ማስታወቂያዎች')}</span><div className="ticker-track"><div className="ticker-items">{[...list,...list].map((n,i)=><Link key={i} href={`/notices/${n.slug}`} tabIndex={i>=list.length?-1:undefined} aria-hidden={i>=list.length||undefined}><b>{n.category}</b>{n[`title_${lang}`]}</Link>)}</div></div><Link className="ticker-all" href="/notices">{t('All notices','ሁሉም')} <ArrowRight size={14}/></Link></div></div>}

export function NoticeBoard(){const {items,lang}=usePortal(),t=useT();const list=items.filter(x=>x.kind==='notices'&&x.published).sort((a,b)=>Number(!!b.pinned)-Number(!!a.pinned)||byDate(a,b));const [featured,...rest]=list;return <section className="wrap section notice-board" aria-labelledby="notice-board-title"><div className="section-heading"><div><div className="eyebrow">{t('NOTICE BOARD','የማስታወቂያ ሰሌዳ')}</div><h2 id="notice-board-title">{t('Public notices & announcements.','ህዝባዊ ማስታወቂያዎች።')}</h2></div><Link href="/notices">{t('All notices','ሁሉም ማስታወቂያዎች')} →</Link></div><div className="notice-layout"><div className="notice-list">{featured&&<Link href={`/notices/${featured.slug}`} className="notice-featured"><div className="notice-featured-top">{featured.pinned&&<span className="pin-chip"><Pin size={13}/>Pinned</span>}<span className="notice-cat">{featured.category}</span><span className="notice-date"><CalendarDays size={14}/>{fmtDate(featured.date)}</span></div><h3>{featured[`title_${lang}`]}</h3><p>{featured[`content_${lang}`]}</p><span className="text-link">{t('Read notice','ማስታወቂያውን ያንብቡ')} <ArrowRight size={16}/></span></Link>}{rest.slice(0,4).map(n=><NoticeRow key={n.slug} item={n}/>)}{!list.length&&<p className="empty">No notices are published at the moment.</p>}</div><aside className="events-card"><h3><CalendarDays size={20}/>{t('Upcoming events','የሚመጡ ዝግጅቶች')}</h3>{events.map(e=><div className="event" key={e.date+e.title}><DateBlock d={e.date}/><div><strong>{e.title}</strong><small><Clock size={13}/>{e.time}</small><small><MapPin size={13}/>{e.place}</small></div></div>)}<p className="events-note">Sample schedule · confirm dates with the department.</p><Link href="/contact" className="text-link">{t('Ask about an event','ስለ ዝግጅት ይጠይቁ')} <ArrowRight size={16}/></Link></aside></div></section>}

export function NoticeRow({item}:{item:Content}){const {lang}=usePortal();const open=!item.deadline||item.deadline>=new Date().toISOString().slice(0,10);return <Link href={`/notices/${item.slug}`} className="notice-row"><DateBlock d={item.date}/><div><span className="notice-cat">{item.category}</span><h3>{item[`title_${lang}`]}</h3>{item.deadline&&<small className={open?'deadline':'deadline closed'}><Clock size={13}/>{open?'Deadline':'Closed'} · {fmtDate(item.deadline)}</small>}</div><ChevronRight size={18}/></Link>}

export function NoticeDetail({item}:{item:Content}){const {items,lang}=usePortal(),t=useT();const others=items.filter(x=>x.kind==='notices'&&x.published&&x.slug!==item.slug).sort(byDate).slice(0,4);const open=!item.deadline||item.deadline>=new Date().toISOString().slice(0,10);return <><Intro title={item[`title_${lang}`]} eyebrow={`${item.category.toUpperCase()} · ${t('PUBLIC NOTICE','ህዝባዊ ማስታወቂያ')}`}>{t('Sample notice for design review.','ለግምገማ የቀረበ ማሳያ ማስታወቂያ።')}</Intro><div className="detail-layout"><article className="panel prose notice-sheet"><div className="notice-sheet-head"><img src="/justice-logo.png" alt="" width="64" height="64"/><div><strong lang="am">የደቡብ ኦሞ ዞን ፍትሕ መምሪያ</strong><span>South Omo Zone Justice Department</span></div><Badge>{item.reference||'Ref. unassigned'}</Badge></div><h2>{item[`title_${lang}`]}</h2><p>{item[`content_${lang}`]}</p>{lang==='en'&&<p lang="am" className="am-summary">{item.content_am}</p>}<dl className="notice-facts"><div><dt>Date posted</dt><dd>{fmtDate(item.date)}</dd></div><div><dt>Deadline</dt><dd>{item.deadline?<>{fmtDate(item.deadline)} <Badge>{open?'Open':'Closed'}</Badge></>:'Not applicable'}</dd></div><div><dt>Reference</dt><dd>{item.reference||'Unassigned — sample'}</dd></div></dl><div className="notice">{<Megaphone size={18}/>}<p>This is illustrative content. Official notices are signed and stamped by the department and published through its approved channels.</p></div></article><aside><div className="panel metadata"><h3>{t('Notice actions','ተግባራት')}</h3><Button onClick={()=>window.print()}><Printer size={16}/> Print notice</Button><Button variant="outline" onClick={()=>copy(window.location.href)}><Copy size={16}/> Copy link</Button><ShareButton title={item.title_en}/></div><div className="panel"><h3>{t('Other notices','ሌሎች ማስታወቂያዎች')}</h3>{others.map(n=><NoticeRow key={n.slug} item={n}/>)}<Link className="text-link" href="/notices">{t('All notices','ሁሉም ማስታወቂያዎች')} <ArrowRight size={16}/></Link></div></aside></div></>}

/* ---------- News ---------- */
export function NewsFeature(){const {items,lang}=usePortal(),t=useT();const list=items.filter(x=>x.kind==='news'&&x.published).sort(byDate);const [lead,...rest]=list;if(!lead)return null;return <section className="wrap section"><div className="section-heading"><div><div className="eyebrow">{t('FROM THE DEPARTMENT','ከመምሪያው')}</div><h2>{t('News & public information.','ዜናና ህዝባዊ መረጃ።')}</h2></div><Link href="/news">{t('All updates','ሁሉም ዜናዎች')} →</Link></div><div className="news-layout"><Link href={`/news/${lead.slug}`} className="news-lead">{lead.image&&<img src={lead.image} alt="" width="1200" height="800"/>}<div><div className="card-meta"><span>{lead.category}</span><span><CalendarDays size={13}/> {fmtDate(lead.date)}</span></div><h3>{lead[`title_${lang}`]}</h3><p>{lead[`content_${lang}`]}</p><span className="text-link">{t('Read full story','ሙሉውን ያንብቡ')} <ArrowRight size={16}/></span></div></Link><div className="news-side">{rest.slice(0,3).map(n=><Link href={`/news/${n.slug}`} className="news-mini" key={n.slug}>{n.image&&<img src={n.image} alt="" width="160" height="107"/>}<div><small>{n.category} · {fmtDate(n.date)}</small><h3>{n[`title_${lang}`]}</h3></div></Link>)}</div></div></section>}

export function NewsArticle({item}:{item:Content}){const {items,lang}=usePortal(),t=useT();const list=items.filter(x=>x.kind==='news'&&x.published).sort(byDate);const i=list.findIndex(x=>x.slug===item.slug),newer=list[i-1],older=list[i+1];const paras=(item.body||[]).map(s=>s.trim()).filter(Boolean);const body=lang==='am'||!paras.length?[item[`content_${lang}`]]:paras;return <article className="article"><header className="article-head"><div className="eyebrow">{item.category.toUpperCase()} · SAMPLE ARTICLE</div><h1>{item[`title_${lang}`]}</h1><p className="article-standfirst">{item[`content_${lang}`]}</p><div className="article-meta"><span><CalendarDays size={15}/>{fmtDate(item.date)}</span><span><User size={15}/>{item.author||'Public Relations Office (sample)'}</span><span><Clock size={15}/>{readMinutes(item)} min read</span></div></header>{item.image&&<figure className="article-cover"><img src={item.image} alt="" width="1200" height="800"/><figcaption>Illustration placeholder · replace with an approved photograph.</figcaption></figure>}<div className="article-body"><div className="article-share" aria-label="Share this article"><span>Share</span><ShareButton title={item.title_en} icon/><Button variant="outline" size="icon" aria-label="Copy link" onClick={()=>copy(window.location.href)}><Copy size={16}/></Button><Button variant="outline" size="icon" aria-label="Print article" onClick={()=>window.print()}><Printer size={16}/></Button></div><div className="prose article-text">{body.map((para,n)=><p key={n}>{para}</p>)}<div className="notice"><Megaphone size={18}/><p>Sample article prepared for portal design review. It does not announce an official decision, event or service change.</p></div></div></div><nav className="article-pager" aria-label="More articles">{older?<Link href={`/news/${older.slug}`}><small><ChevronLeft size={14}/> {t('Previous story','ቀዳሚ')}</small><strong>{older[`title_${lang}`]}</strong></Link>:<span/>}{newer?<Link href={`/news/${newer.slug}`} className="next"><small>{t('Next story','ቀጣይ')} <ChevronRight size={14}/></small><strong>{newer[`title_${lang}`]}</strong></Link>:<span/>}</nav></article>}

function ShareButton({title,icon=false}:{title:string;icon?:boolean}){async function share(){const url=window.location.href;if(navigator.share){try{await navigator.share({title,url})}catch{}}else copy(url)}return icon?<Button variant="outline" size="icon" aria-label="Share" onClick={share}><Share2 size={16}/></Button>:<Button variant="outline" onClick={share}><Share2 size={16}/> Share</Button>}

/* ---------- Gallery ---------- */
function Lightbox({list,index,setIndex}:{list:GalleryItem[];index:number|null;setIndex:(i:number|null)=>void}){const {lang}=usePortal();const item=index===null?null:list[index];useEffect(()=>{if(index===null)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setIndex((index+1)%list.length);if(e.key==='ArrowLeft')setIndex((index-1+list.length)%list.length)};window.addEventListener('keydown',onKey);return ()=>window.removeEventListener('keydown',onKey)},[index,list.length,setIndex]);return <Dialog open={!!item} onOpenChange={o=>{if(!o)setIndex(null)}}><DialogContent className="lightbox">{item&&<><div className="lightbox-stage"><img src={item.src} alt={item.title_en}/>{list.length>1&&<><button className="lb-prev" aria-label="Previous image" onClick={()=>setIndex((index!-1+list.length)%list.length)}><ChevronLeft/></button><button className="lb-next" aria-label="Next image" onClick={()=>setIndex((index!+1)%list.length)}><ChevronRight/></button></>}</div><div className="lightbox-info"><DialogTitle>{item[`title_${lang}`]}</DialogTitle><DialogDescription>{item.caption}</DialogDescription><small>{item.category} · {fmtDate(item.date)} · {item.credit} · {index!+1} / {list.length}</small></div></>}</DialogContent></Dialog>}

function GalleryGrid({list,limit}:{list:GalleryItem[];limit?:number}){const {lang}=usePortal();const [open,setOpen]=useState<number|null>(null);const shown=limit?list.slice(0,limit):list;return <><div className="gallery-grid">{shown.map((g,i)=><button key={g.id} className={'gallery-tile'+(i===0?' wide':'')} onClick={()=>setOpen(i)} aria-label={`Open image: ${g.title_en}`}><img src={g.src} alt="" loading="lazy"/><span className="gallery-caption"><small>{g.category}</small><strong>{g[`title_${lang}`]}</strong></span><Expand className="gallery-zoom" size={18}/></button>)}</div><Lightbox list={shown} index={open} setIndex={setOpen}/></>}

export function GallerySection(){const {gallery}=usePortal(),t=useT();return <section className="gallery-band"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">{t('PHOTO GALLERY','የፎቶ ማዕከል')}</div><h2>{t('Moments from our work.','ከስራችን የተወሰዱ ምስሎች።')}</h2></div><Action href="/gallery" outline>{t('View full gallery','ሙሉ ማዕከሉን ይመልከቱ')}</Action></div><GalleryGrid list={gallery} limit={6}/></div></section>}

export function GalleryPage(){const {gallery}=usePortal(),t=useT();const cats=useMemo(()=>['All',...new Set(gallery.map(g=>g.category))],[gallery]);const [cat,setCat]=useState('All');const list=gallery.filter(g=>cat==='All'||g.category===cat);return <><Intro title={t('Photo gallery','የፎቶ ማዕከል')} eyebrow="MEDIA">{t('Images from department activities, offices and the South Omo region. Illustrations mark where approved photographs will appear.','የመምሪያው እንቅስቃሴዎች ምስሎች።')}</Intro><div className="chip-row" role="group" aria-label="Filter by category">{cats.map(c=><button key={c} className={c===cat?'chip active':'chip'} aria-pressed={c===cat} onClick={()=>setCat(c)}>{c}</button>)}</div><p className="result-count" aria-live="polite">{list.length} {list.length===1?'image':'images'}</p><GalleryGrid key={cat} list={list}/></>}

export function GalleryManager(){const p=usePortal();const editable=['Super Administrator','Public Relations Officer'].includes(p.role);const [title,setTitle]=useState(''),[category,setCategory]=useState('Events'),[caption,setCaption]=useState(''),[file,setFile]=useState<File|null>(null);function add(e:React.FormEvent){e.preventDefault();if(!file||!editable)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>8*1024*1024){toast.error('Choose a JPG, PNG or WebP image up to 8 MB.');return}const item:GalleryItem={id:'u'+crypto.randomUUID().slice(0,8),src:URL.createObjectURL(file),title_en:title,title_am:title,caption:caption||'Uploaded during this session.',category,date:new Date().toISOString().slice(0,10),credit:'Uploaded in preview (session only)'};p.setGallery(g=>[item,...g]);p.log('Gallery image added: '+title);setTitle('');setCaption('');setFile(null);(e.target as HTMLFormElement).reset();toast.success('Image added to the public gallery for this session')}return <><Intro title="Gallery">Add or remove images shown on the homepage and gallery page. Images stay in this browser session only.</Intro>{!editable&&<p className="notice">Your selected demo role has read-only access to the gallery.</p>}<form className="panel gallery-form" onSubmit={add}><h2><Upload size={20}/> Add image</h2><div className="form-grid"><Field label="Title *" required value={title} onChange={e=>setTitle(e.target.value)} disabled={!editable}/><Field label="Category *" required value={category} onChange={e=>setCategory(e.target.value)} disabled={!editable}/></div><Field label="Caption" value={caption} onChange={e=>setCaption(e.target.value)} disabled={!editable}/><label className="field"><span>Image file * (JPG, PNG or WebP · max 8 MB)</span><Input type="file" accept="image/jpeg,image/png,image/webp" required disabled={!editable} onChange={e=>setFile(e.target.files?.[0]||null)}/></label><Button type="submit" disabled={!editable||!file||!title.trim()}><Images size={16}/> Add to gallery</Button></form><div className="admin-gallery">{p.gallery.map(g=><div className="panel" key={g.id}><img src={g.src} alt=""/><div><strong>{g.title_en}</strong><small>{g.category} · {fmtDate(g.date)}</small></div><Button variant="outline" size="icon" aria-label={'Remove '+g.title_en} disabled={!editable} onClick={()=>{p.setGallery(a=>a.filter(x=>x.id!==g.id));p.log('Gallery image removed: '+g.title_en)}}><Trash2 size={16}/></Button></div>)}</div></>}

/* ---------- FAQ, newsletter, back to top ---------- */
export function FaqPage(){const t=useT();return <><Intro title={t('Frequently asked questions','ተደጋግመው የሚጠየቁ ጥያቄዎች')}>{t('Quick answers about complaints, offices and public legal information.','ስለ ቅሬታ፣ ቢሮዎችና የህግ መረጃ ፈጣን መልሶች።')}</Intro><div className="two-col faq-layout"><Accordion type="single" collapsible className="panel faq">{faqs.map(([q,a],i)=><AccordionItem value={'q'+i} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion><aside className="help-card"><FileText size={28}/><h3>Still have a question?</h3><p>Contact the department or visit your nearest woreda justice office.</p><Link href="/contact">Contact the department →</Link><Link href="/offices">Find an office →</Link><Link href="/forms">Downloadable forms <Download size={14}/></Link></aside></div></>}

export function Newsletter(){const [done,setDone]=useState(false);return <form className="newsletter" onSubmit={e=>{e.preventDefault();setDone(true);toast.success('Subscription recorded for this demo — no email will be sent.')}}><h4><Mail size={16}/> Notice alerts</h4>{done?<p role="status">Thank you. This preview does not send email.</p>:<><p>Get new notices and news by email.</p><div><Input type="email" required placeholder="you@example.com" aria-label="Email address"/><Button type="submit">Subscribe</Button></div></>}</form>}

export function BackToTop(){const [show,setShow]=useState(false);useEffect(()=>{const on=()=>setShow(window.scrollY>600);on();window.addEventListener('scroll',on,{passive:true});return ()=>window.removeEventListener('scroll',on)},[]);return show?<button className="back-to-top" aria-label="Back to top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><ArrowUp size={20}/></button>:null}
