export type Content = {slug:string;kind:string;title_en:string;title_am:string;content_en:string;content_am:string;category:string;year:string;published:boolean;date?:string;image?:string;body?:string[];author?:string;deadline?:string;reference?:string;pinned?:boolean};
export const records:Content[] = [
 ['citizens-charter','laws',"Citizens’ Charter",'የዜጎች ቻርተር','A sample guide to respectful service, clear information, equal treatment and complaint channels. Ask the responsible office to confirm service requirements, fees and response times.','ይህ የአገልግሎት መረጃ ማሳያ ነው። መስፈርቶችን ከሚመለከተው ቢሮ ያረጋግጡ።','Policies'],
 ['legal-awareness','laws','Public Legal Awareness Material','የህግ ግንዛቤ መመሪያ','Prepare questions before visiting a justice office. Keep copies of correspondence and ask for an explanation of the next step. This sample is educational material, not legislation or legal advice.','ወደ ፍትሕ ቢሮ ከመሄድዎ በፊት ጥያቄዎችዎን ያዘጋጁ። ይህ ለማሳያ የተዘጋጀ መረጃ ነው።','Legal Awareness'],
 ['crime-prevention','laws','Crime Prevention Strategy','የወንጀል መከላከል ስትራቴጂ','Sample discussion framework: community awareness, accessible reporting, coordination between public offices and respectful support for people affected by crime.','የማህበረሰብ ግንዛቤና የተቋማት ትብብር ለማሳያ የቀረቡ ርዕሶች ናቸው።','Strategies'],
 ['administrative-justice','laws','Administrative Justice Guideline','የአስተዳደር ፍትሕ መመሪያ','Sample checklist for recording a concern, identifying the responsible office, communicating progress and explaining an outcome. No official proclamation number has been assigned to this demonstration.','ቅሬታን ለመመዝገብና ሂደቱን ለማሳወቅ የተዘጋጀ ማሳያ።','Directives'],
 ['complaint-support','services','Complaint reception & guidance','የቅሬታ አቀባበልና መመሪያ','Get help describing a concern and identifying the relevant office. Bring a written summary and copies of supporting correspondence, if available.','ቅሬታዎን ለማቅረብ መመሪያ ያግኙ። ካለዎት ደጋፊ ሰነድ ቅጂ ይያዙ።','Citizen services'],
 ['legal-information','services','Legal information & awareness','የህግ መረጃና ግንዛቤ','Find public information materials and learn where to request further assistance. Staff can help identify resources relevant to your question.','የህግ መረጃ ያግኙ፤ ለተጨማሪ እርዳታ የሚመለከተውን ቢሮ ያነጋግሩ።','Information'],
 ['mediation-referral','services','Reconciliation & referral guidance','የእርቅና የቅብብሎሽ መመሪያ','Ask about appropriate referral pathways, voluntary participation and available formal justice options. Suitability must be assessed by an authorized professional.','ስለ እርቅና የፍትሕ አማራጮች መረጃ ያግኙ።','Referral'],
 ['community-dialogue','customary-justice','Community dialogue & reconciliation','የማህበረሰብ ውይይትና እርቅ','This sample introduces questions for community-led documentation: Who participates? How is consent established? How are agreements recorded? What safeguards and formal justice alternatives are available? Community-specific accounts require consent, research references and local review before publication.','ይህ ማሳያ ስለ ተሳትፎ፣ ፈቃድና የእርቅ ሂደት የውይይት ጥያቄዎችን ያቀርባል። ህትመት የማህበረሰቡን ግምገማ ይፈልጋል።','Reconciliation'],
 ['elders-and-participation','customary-justice','Documenting the role of elders','የሽማግሌዎችን ሚና መመዝገብ','A research outline for documenting local perspectives without treating communities as identical. Include women, young people and other affected participants. Distinguish personal accounts from verified research and avoid publishing sensitive disputes.','የአካባቢ አመለካከቶችን በአክብሮት ለመመዝገብ የተዘጋጀ የምርምር ማሳያ።','Research'],
 ['portal-preview','news','A clearer path to public justice services','የፍትሕ አገልግሎቶችን በቀላሉ ያግኙ','Explore the new portal prototype: browse sample resources, walk through a complaint and follow its progress. This demonstration is open for design review; it does not receive official complaints.','በዚህ ማሳያ የቅሬታ ሂደትን ይሞክሩ፤ የመረጃ ሰነዶችን ይመልከቱ። እውነተኛ ቅሬታ አይቀበልም።','Announcements'],
 ['service-preparation','news','Before you visit your justice office','ወደ ፍትሕ ቢሮ ከመሄድዎ በፊት','Write down your question, collect relevant documents and confirm office opening hours before travelling. Keep original documents safe and take copies where possible. Sample public information article.','ጥያቄዎን ይጻፉ፤ ሰነዶችዎን ያዘጋጁ፤ የስራ ሰዓትን ያረጋግጡ።','Public Notices'],
 ['research-invitation','news','Preserving knowledge through respectful research','እውቀትን በአክብሮት መጠበቅ','Sample editorial brief: community-reviewed research can help explain customary justice and its relationship with public institutions. No event or official consultation is announced by this sample.','ማሳያ፦ በማህበረሰብ የተገመገመ ምርምር ባህላዊ ፍትሕን ለመረዳት ይረዳል።','Weekly Updates'],
 ['complaint-form','forms','Complaint preparation form','የቅሬታ ማዘጋጃ ቅጽ','Sample form: complaint title, office concerned, incident date, description, previous action and preferred response. Do not include unnecessary sensitive information.','ማሳያ፦ የቅሬታ ርዕስ፣ ቢሮ፣ ቀንና መግለጫ።','Complaints'],
 ['information-request','forms','Public information request','የመረጃ ጥያቄ ቅጽ','Sample form: describe the public information requested, preferred format and relevant dates. Confirm the official procedure with the responsible office.','የሚፈልጉትን መረጃ ይግለጹ። የአሰራሩን ሂደት ከቢሮው ያረጋግጡ።','Information']
].map(([slug,kind,title_en,title_am,content_en,content_am,category])=>({slug,kind,title_en,title_am,content_en,content_am,category,year:'2026',published:true}));
export const woredas=['Jinka','Bena Tsemay','Hamer','Dasenech','South Ari','North Ari','Male','Nyangatom'];
export const categories=['Service Delay','Administrative Complaint','Good Governance Issue','Corruption Report','Employee Conduct','Justice Service Complaint','Other'];
export const statuses=['Submitted','Received','Under Review','Assigned','Investigation / Processing','Response Prepared','Resolved','Closed','More Information Required','Referred','Rejected'];
export type CaseRecord={id:string;secret:string;title:string;category:string;office:string;description:string;anonymous:boolean;status:string;priority:string;assigned:string;date:string;history:{status:string;date:string}[];notes:string[];responses:string[]};
export const sampleCases:CaseRecord[]=[['DEMO-2026-0142','Service follow-up','Service Delay','Jinka','Under Review'],['DEMO-2026-0141','Request for public information','Administrative Complaint','Hamer','Received'],['DEMO-2026-0140','Referral guidance','Justice Service Complaint','Bena Tsemay','Resolved']].map(([id,title,category,office,status])=>({id,secret:'DEMO1234',title,category,office,description:'Fictional case for demonstrating the complaint workflow. No real person or incident is represented.',anonymous:true,status,priority:'Normal',assigned:'Unassigned',date:'2026-09-28',history:[{status:'Submitted',date:'2026-09-28'},{status,date:'2026-09-28'}],notes:[],responses:[]}));

// Extended article details for news items (merged into records by slug).
const newsDetails:Record<string,Partial<Content>>={
 'portal-preview':{date:'2026-09-24',image:'/gallery/portal-launch.svg',author:'Public Relations Office (sample)',body:['The South Omo Zone Justice Department is reviewing a new digital portal designed to make public justice information easier to find and citizen services easier to understand.','The prototype brings together service guidance, a legal document library, a customary justice knowledge hub and a guided complaint process with reference tracking. Every workflow is written in plain language and designed to work on mobile phones as well as office computers.','During the review period, the portal does not receive official complaints. Reviewers are invited to walk through each step using fictional information and share feedback on clarity, accessibility and translation.','Once approved, the department intends to connect verified content, protected case storage and staff accounts before any public launch.']},
 'service-preparation':{date:'2026-09-17',image:'/gallery/legal-awareness.svg',author:'Citizen Services Desk (sample)',body:['A little preparation can make a visit to a justice office quicker and less stressful.','Write down your question or concern in a few sentences. Include relevant dates, the names of offices you have already contacted and the outcome you are hoping for.','Collect documents that relate to your concern. Keep the originals safe and bring copies where possible. If you are unsure which documents matter, bring what you have and ask the service desk.','Confirm opening hours before travelling, especially around public holidays. Ask staff to explain the next step and any reference number you are given, and keep it for follow-up.']},
 'research-invitation':{date:'2026-09-10',image:'/gallery/community-dialogue.svg',author:'Customary Justice Hub (sample)',body:['Customary dispute resolution plays an important role in many South Omo communities. Documenting it respectfully helps explain how it relates to formal public institutions.','This sample editorial brief describes principles for community-reviewed research: informed consent, inclusion of women and young people, clear attribution, and a distinction between personal accounts and verified findings.','No event or official consultation is announced by this sample article. Any future research programme would be announced through the department’s official channels.']},
 'woreda-outreach':{date:'2026-09-03',image:'/gallery/woreda-office.svg',author:'Coordination Office (sample)',body:['Justice information is most useful when it reaches people close to where they live. This sample article describes an outreach approach for woreda justice offices.','Outreach sessions could combine short talks on rights and service pathways with time for individual questions. Printed materials in local languages help people keep information after the session.','Dates, locations and participating offices are illustrative and require confirmation before publication.']},
 'legal-aid-week':{date:'2026-08-27',image:'/gallery/legal-aid.svg',author:'Legal Information Directorate (sample)',body:['Free legal information days help citizens understand their options before a dispute escalates.','This sample article outlines how a legal information week might work: information desks at zonal and woreda offices, short awareness sessions, and referral guidance for people who need further assistance.','Legal information is not legal advice. Where representation is needed, staff can explain available referral pathways.']}
};
records.push(
 {slug:'woreda-outreach',kind:'news',title_en:'Bringing justice information closer to woredas',title_am:'የፍትሕ መረጃን ወደ ወረዳዎች ማቅረብ',content_en:'A sample outreach approach for woreda justice offices: short talks on rights and service pathways, printed materials and time for individual questions.',content_am:'ለወረዳ ፍትሕ ጽ/ቤቶች የተዘጋጀ የማዳረስ ማሳያ።',category:'Weekly Updates',year:'2026',published:true},
 {slug:'legal-aid-week',kind:'news',title_en:'Legal information week: what to expect',title_am:'የህግ መረጃ ሳምንት፦ ምን ይጠበቃል',content_en:'Information desks, short awareness sessions and referral guidance help citizens understand their options before a dispute escalates. Sample article.',content_am:'የመረጃ ዴስኮችና የግንዛቤ ክፍለ ጊዜዎች — ማሳያ ጽሑፍ።',category:'Announcements',year:'2026',published:true}
);
records.forEach(r=>{if(newsDetails[r.slug])Object.assign(r,newsDetails[r.slug])});

// Notice board (sample). Deadlines and reference numbers are illustrative.
records.push(...([
 ['holiday-hours','Office hours during the Meskel holiday','በመስቀል በዓል ወቅት የስራ ሰዓት','All zonal and woreda justice offices will observe public holiday hours. Services resume on the next working day. Please confirm locally before travelling.','አገልግሎት በቀጣዩ የስራ ቀን ይቀጥላል።','Announcement','2026-09-25','','SOJD/N/2026/014',true],
 ['vacancy-legal-officer','Vacancy: Legal Awareness Officer (sample)','የስራ ማስታወቂያ፦ የህግ ግንዛቤ ባለሙያ','Sample vacancy notice. Requirements, number of positions and application procedure must be confirmed with the Human Resources unit. No real recruitment is announced.','የማሳያ የስራ ማስታወቂያ።','Vacancy','2026-09-22','2026-10-10','SOJD/HR/2026/031',false],
 ['public-consultation','Invitation to comment on the citizens’ charter draft','በዜጎች ቻርተር ረቂቅ ላይ አስተያየት','Citizens and community organizations are invited to review the sample citizens’ charter and share comments on clarity and accessibility. Sample notice for design review.','በዜጎች ቻርተር ረቂቅ ላይ አስተያየት ይስጡ።','Public Consultation','2026-09-19','2026-10-20','SOJD/N/2026/012',false],
 ['tender-office-supplies','Procurement notice: office supplies (sample)','የግዥ ማስታወቂያ፦ የቢሮ ዕቃዎች','Sample procurement notice. Eligibility, bid documents and deadlines are illustrative and must be replaced with the approved notice before publication.','የማሳያ የግዥ ማስታወቂያ።','Tender','2026-09-15','2026-10-05','SOJD/PR/2026/007',false],
 ['service-desk-relocation','Citizen service desk moves to the ground floor','የዜጎች አገልግሎት ዴስክ ወደ መሬት ወለል ተዛወረ','To improve accessibility, the sample citizen service desk at the zonal office now operates from the ground floor near the main entrance.','ለተደራሽነት ሲባል የአገልግሎት ዴስክ ተዛውሯል።','Announcement','2026-09-08','','SOJD/N/2026/010',false]
] as const).map(([slug,title_en,title_am,content_en,content_am,category,date,deadline,reference,pinned])=>({slug,kind:'notices',title_en,title_am,content_en,content_am,category,year:'2026',published:true,date,deadline:deadline||undefined,reference,pinned})));

export type GalleryItem={id:string;src:string;title_en:string;title_am:string;caption:string;category:string;date:string;credit:string};
export const galleryItems:GalleryItem[]=[
 {id:'g1',src:'/omo-landscape.jpg',title_en:'Lower Valley of the Omo',title_am:'የታችኛው ኦሞ ሸለቆ',caption:'The landscape of South Omo, home to diverse communities served by the department.',category:'Region',date:'2015-04-16',credit:'Karalyn Monteil / UNESCO · CC BY-SA 3.0 IGO'},
 {id:'g2',src:'/gallery/community-dialogue.svg',title_en:'Community dialogue session',title_am:'የማህበረሰብ ውይይት',caption:'Illustration — replace with an approved, consented event photograph.',category:'Community',date:'2026-09-10',credit:'Illustration placeholder'},
 {id:'g3',src:'/gallery/legal-awareness.svg',title_en:'Legal awareness training',title_am:'የህግ ግንዛቤ ስልጠና',caption:'Illustration — replace with an approved event photograph.',category:'Training',date:'2026-09-17',credit:'Illustration placeholder'},
 {id:'g4',src:'/gallery/woreda-office.svg',title_en:'Woreda justice office',title_am:'የወረዳ ፍትሕ ጽ/ቤት',caption:'Illustration — replace with an approved office photograph.',category:'Offices',date:'2026-09-03',credit:'Illustration placeholder'},
 {id:'g5',src:'/gallery/portal-launch.svg',title_en:'Digital portal review',title_am:'የዲጂታል ፖርታል ግምገማ',caption:'Illustration — replace with an approved photograph.',category:'Events',date:'2026-09-24',credit:'Illustration placeholder'},
 {id:'g6',src:'/gallery/legal-aid.svg',title_en:'Legal information desk',title_am:'የህግ መረጃ ዴስክ',caption:'Illustration — replace with an approved event photograph.',category:'Events',date:'2026-08-27',credit:'Illustration placeholder'},
 {id:'g7',src:'/justice-logo.png',title_en:'Bureau of Justice emblem',title_am:'የፍትሕ ቢሮ አርማ',caption:'The regional Bureau of Justice emblem: the scales, the pillar of law, the dove of peace and the open book.',category:'Institution',date:'2026-09-01',credit:'Regional Bureau of Justice'}
];

export const faqs:[string,string][]=[
 ['Do I need an account to submit a complaint?','No. You can submit a complaint without an account. You will receive a tracking number and a private access code to follow its progress.'],
 ['Can I report anonymously?','Yes. The anonymous report option does not ask for your name or contact details. Keep your tracking details, because the department cannot contact you directly.'],
 ['How long does it take to receive a response?','Response times depend on the type of complaint and the office involved. Official service standards will be published in the approved citizens’ charter.'],
 ['Which office should I contact?','Start with the woreda justice office closest to you. If you are unsure, the zonal citizen service desk in Jinka can direct you to the right office.'],
 ['Is the information on this portal legal advice?','No. The portal provides general public legal information. For advice about your specific situation, ask the relevant office about referral pathways.'],
 ['Are services available in Amharic?','Yes. The main navigation and key pages are available in Amharic. Full translation of every page is in progress.']
];

export type EventItem={date:string;title:string;place:string;time:string};
export const events:EventItem[]=[
 {date:'2026-10-06',title:'Legal awareness session (sample)',place:'Jinka zonal office hall',time:'09:00 – 11:30'},
 {date:'2026-10-14',title:'Woreda coordination meeting (sample)',place:'Hamer woreda office',time:'14:00 – 16:00'},
 {date:'2026-10-22',title:'Citizens’ charter consultation (sample)',place:'Online & Jinka',time:'10:00 – 12:00'}
];
